### ISSUE TITLE
All content deleted suddenly

### ISSUE THREAD

**Issue by turelmert** [GitbookIO/gitbook-cli#116]
While in edit mode within a change request, all my changes deleted and saved within that change request. I cannot find it anywhere it is not in drafts, archived or in change request. I also checked original content but couldn't find my changes.

**Comment by ywu36** [comment]
this is the fuckness of gitbook

**Comment by ywu36** [comment]
I lost eveything too

**Comment by satyam-mishra-pce** [comment]
I lost everything too. It was like 10 full pages.
