### ISSUE TITLE
Odd difference between gitbook build and the gitbook editor

### ISSUE THREAD

**Issue by davidmoshal** [GitbookIO/gitbook-cli#14]
The following snippet works in Gitbook Editor, but fails using the command line `gitbook build` !

```
![alt](http://g.gravizo.com/g?
  @startsalt;
  {{T;
  + dir1;
  ++ dir2;
  +++ dir3;
  +;
  }};
  @endsalt;
)
```

with this error:
```
Template render error: (/overview/directory_structure.md)
  ReferenceError: Invalid left-hand side expression in prefix operation (In file 'overview/directory_structure.md')
```

The problem seems to be the line `  +++ dir3;`.
For some strange reason 3 or more `+` signs cause a problem, but only with gitbook cli not with Gitbook Editor !

**Comment by davidmoshal** [comment]
No takers??

**Comment by SamyPesse** [comment]
`{{` and `}}` are used in the [templating syntax](http://help.gitbook.com/format/templating.html). The editor doesn't process the templating syntax.

You can use `{% raw %}` and `{% endraw %}`:

```
{% raw %}
![alt](http://g.gravizo.com/g?
  @startsalt;
  {{T;
  + dir1;
  ++ dir2;
  +++ dir3;
  +;
  }};
  @endsalt;
)
{% endraw %}
```

**Comment by davidmoshal** [comment]
Thanks, that worked, as did putting a semi-colon between the `}}`:
i.e:
```
{;{;
...
};};
```
(It helped knowing what the problem was - should have figured it out myself).
