### ISSUE TITLE
Running 'gitbook *'

### ISSUE THREAD

**Issue by imcaffrey** [GitbookIO/gitbook-cli#15]
While running `gitbook *`

It told me that 'Command a doesn't exist' instead of 'Command * doesn't exist'.

Is that right?

https://github.com/GitbookIO/gitbook-cli/blob/master/lib/commands.js#L27

**Comment by SamyPesse** [comment]
Why are you running `gitbook *` ? It can't work, `sh` will run `gitbook <file>` for each files, so I guess you have a file named `a`.

**Comment by imcaffrey** [comment]
Thanks for informing.
