### ISSUE TITLE
Can't install latest version

### ISSUE THREAD

**Issue by znmeb** [GitbookIO/gitbook-cli#2]
Fedora Linux: I installed gitbook-cli via `sudo npm install -g gitbook-cli`. Then I entered my Gitbook source directory and tried to build the book:

```
$ gitbook serve
Installing version 2.0.0-alpha.5
\
Error: Command failed: fatal: bad object 58d8ea24b9b7b4137ee5f30a41abce4d7c4a922a
```

**Comment by SamyPesse** [comment]
Can you please add the argument `-d`: `gitbook serve -d`, that will give us the stack trace of the error.

**Comment by MrMaksimize** [comment]
Getting the same problem :)  

```
Installing version 2.0.0-alpha.5
-
Error: Command failed: fatal: bad object 58d8ea24b9b7b4137ee5f30a41abce4d7c4a922a

Error: Command failed: fatal: bad object 58d8ea24b9b7b4137ee5f30a41abce4d7c4a922a

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

**Comment by SamyPesse** [comment]
Are you also using linux ? did you install it using "sudo npm install ..." ?

**Comment by SamyPesse** [comment]
Ok, it should now work fine and install the `2.0.0-alpha.6`.

**Comment by znmeb** [comment]
Yup - working now. Two warnings:

1. I am using the autocover plugin. The 'gitbook serve' command auto-installed 2.0.0-alpha.6 but then noticed the autocover plugin and exited, telling me to run 'gitbook install'. You might want to tack that on to the first install step, since it seems to be a wrapper on npm.
2. The Gitbook version isn't in my book.json. Somewhere that specification should be documented.
