### ISSUE TITLE
doesn't work on Mac OS X 10.9

### ISSUE THREAD

**Issue by christian-posta** [GitbookIO/gitbook-cli#24]
Running (help, init, build) does not work, i get this error:

> Error: Invalid version or tag "undefined", see available using "gitbook ls-remote"

Here's the output of ~/.gitbook/versions:

> ceposta@postamac(test-book (master)) $ ll ~/.gitbook/versions/
> total 0
> drwxr-xr-x  20 ceposta  staff   680B Mar  4 13:34 2.6.7

npm version

ceposta@postamac(test-book (master)) $ npm version
{ npm: '3.6.0',
  ares: '1.10.1-DEV',
  http_parser: '2.6.2',
  icu: '56.1',
  modules: '47',
  node: '5.7.1',
  openssl: '1.0.2g',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }

**Comment by christian-posta** [comment]
tried same thing on a different mac and with an older version of gitbook... same result

**Comment by SamyPesse** [comment]
What is the content of your `book.json` ?

**Comment by SamyPesse** [comment]
Please try again with `gitbook-cli@2.1.2`

**Comment by christian-posta** [comment]
Sorry for the alarm, bad book.json... damn missing commas!!!
