### ISSUE TITLE
Livereload in serve

### ISSUE THREAD

**Issue by nyarly** [GitbookIO/gitbook-cli#3]
It'd be rad if the served book would update live instead of on browser reload. In the meantime I'm using markdownd for general work.

**Comment by SamyPesse** [comment]
Already implemented in `gitbook serve` (https://github.com/GitbookIO/gitbook/blob/master/lib/index.js#L147)

**Comment by josephkandi** [comment]
This doesnt seem to work when am using the Gitbook Editor 5.0.2. After the update i have to manually reload and sometimes my changes do not show up until i quit Gitbook Editor and re-open then they will show up.
