### ISSUE TITLE
gitbook-cli@2.3.1 fails to run gitbook init

### ISSUE THREAD

**Issue by sargant** [GitbookIO/gitbook-cli#68]
```
# node -v
v8.1.4

# npm -v
5.0.3

# npm install -g gitbook-cli@2.3.1
# gitbook fetch
# gitbook --version
CLI version: 2.3.1
GitBook version: 3.2.2

# gitbook init
Error loading version latest: Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/.gitbook/versions/3.2.2/lib/index.js:1:76)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

TypeError: Cannot read property 'commands' of null
```

**Comment by sargant** [comment]
`gitbook-cli@2.3.1` fails for every environment I've tested:

`node@8.1.4 npm@5.0.3` fails
`node@6.11.1 npm@3.10.10` fails
`node@4.8.4 npm@2.15.11` fails

`gitbook-cli@2.3.0` works fine on all these platforms

**Comment by AaronO** [comment]
I think the issue is that `gitbook-cli` uses `npm` as a library to install different versions of `gitbook`. We upgraded fron `npm@3.x.x` to `npm@5.x.x` in the last release, so it's likely due to differences in NPM's behavior our approach no longer works.

Would need to dig into this.

https://github.com/GitbookIO/gitbook/issues/1818

**Comment by kozi** [comment]
Got the same problem! `npm@8.1.4` and `npm@5.2.0` No luck with `gitbook-cli@2.3.0` or `gitbook-cli@2.3.1`

**Comment by dtolb** [comment]
Same issue in travis, local, work etc... 
From the [thread](https://github.com/GitbookIO/gitbook/issues/1818) over in the gitbook repo per @oblador:

`cd ~/.gitbook/versions/3.2.2 && npm i`

Should work.

**Comment by GuGuss** [comment]
Same issue here when deploying Platform.sh documentation.

I'm currently sticking the `gitbook-cli` version to `2.3.0` (see Pull Request here: https://github.com/platformsh/platformsh-docs/pull/583)

**Comment by greatdreams** [comment]
@dtolb Your solution is OK for this problem. Thanks!  In addition, I 've tried to uninstall gitbook-cli@2.3.1 and install gitbook-cli@2.3.0,  the problem is solved too. The detail is:

# node -v
v8.1.4

# npm -v 5.0.3
5.0.3

# npm install -g gitbook-cli@2.3.0

**Comment by greatdreams** [comment]
@dtolb Your solution is OK for this problem. Thanks! In addition, I 've tried to uninstall gitbook-cli@2.3.1 and install gitbook-cli@2.3.0, the problem is solved too. The detail is:

```bash
$ node -v
v8.1.4
$ npm -v 
5.0.3
$ rm -rvf ~/.gitbook
$ npm install -g gitbook-cli@2.3.0
```

**Comment by dtolb** [comment]
@greatdreams I did the same thing for my automated builds https://github.com/Bandwidth/bandwidth.github.io/pull/58/files

**Comment by greatdreams** [comment]
@dtolb I think that I've found it.  it's `npmi@2.0.1` which makes the bug.  I've tried to use `npmi@1.0.1`  in gitbook-cli@2.3.1 and it works.  

I've use two environments to test it. 
1. `npm@5.0.3, node@8.1.4`
2. ` npm@3.10.8, node 6.9.1`

We can explore different behavior of npmi from 1.0.1 to 2.0.2, and test it.

Details of test steps:
```
$ node -v
v8.1.4
$ npm -v 
5.0.3
$ rm -rvf ~/.gitbook
$ npm install -g gitbook-cli@2.3.1
```
delete node_modules of gitbook-cli 
change `npmi@2.0.1` to `npmi@1.0.1` in package.json of gitbook-cli
in gitbook-cli installation directory, and run `npm install`

Now,
```
$ gitbook fetch
$ gitbook -V
CLI version: 2.3.1
GitBook version: 3.2.2
$ gitbook init
warn: no summary file in this book 
info: create README.md 
info: create SUMMARY.md 
info: initialization is finished 
```
It works!

**Comment by WHY1121** [comment]
# node -v
v6.10.2

# npm -v
3.10.10

#npm install -g gitbook-cli@2.3.1
# gitbook --version
CLI version: 2.3.1
GitBook version: 3.2.2

# gitbook install
Error loading version latest: Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/.gitbook/versions/3.2.2/lib/index.js:1:76)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

TypeError: Cannot read property 'commands' of null

**Comment by gabm** [comment]
I was able to reproduce with several node versions from 8 through 6... its clearly a problem in gitbook-cli

**Comment by AaronO** [comment]
This should now be fixed in the `2.3.2` release

**Comment by werne2j** [comment]
This is still an issue. See #70

**Comment by jLouzado** [comment]
still an issue in v3.2.3

**Comment by jLouzado** [comment]
+1

still seen on gitbook-cli 2.3.2

**Comment by fpagnoux** [comment]
Same here, I had to downgrade to node 6 and npm 3 to get gitbook to work...
