### ISSUE TITLE
Update to a newer version of npmi to prevent node-uuid warning

### ISSUE THREAD

**Issue by edmorley** [GitbookIO/gitbook-cli#72]
Hi!

`gitbook-cli@2.3.2` has a strict dependency on `npmi@1.0.1`, which itself depends on `npm@^2.1.12` (currently 2.15.12), which depends on `request@~2.74.0`, which still uses the deprecated `node-uuid` package.

Unfortunately this results in:
```
[1/4] Resolving packages...
warning node-uuid@1.4.8: Use uuid module instead
```

Please could gitbook-cli be updated to use a newer npmi, thereby preventing the noise from this warning? :-)

**Comment by prescottprue** [comment]
Been seeing this too.
