### ISSUE TITLE
Installation help: "Peer's Certificate issuer is not recognized"

### ISSUE THREAD

**Issue by fipp** [GitbookIO/gitbook-cli#9]
Hi. Hope it's allright that I ask this here. I'm trying to install gitbook-cli on my CentOS 7 box, but fail:
```
# sudo npm install -g gitbook-cli
...
# gitbook init
Installing version 2.1.0
-
Error: Command failed: fatal: unable to access 'https://github.com/mozilla/nunjucks/': Peer's Certificate issuer is not recognized.
```

I do not understand why I am getting this error message. I've tried wget, curl, and creating a simple nodejs script to request 'https://github.com/mozilla/nunjucks/', all without problems.

Any pointers to where I might look to resolve this issue would be greatly appreciated!

**Comment by fipp** [comment]
My fault. In my git settings, I'd specified a specific CA with http.sslCAInfo not reckognizing github...

**Comment by Ilmn-Ybi** [comment]
Hi, our users got the same error with GitHub Enterprise we just installed.

Can you elaborate with more details so we can use your solution?

Thanks!
